version: '3'
services:
#mssql docker
  mdome-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - mdomenet

  mdome-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:mDome=Server=mdome-sql,1433;Database=170052;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 61090:80
    networks:
      - mdomenet      
    links:
      - mdome-sql
    depends_on:
      - mdome-sql

networks:
  mdomenet:
    driver: bridge       